# Generated by Django 3.0.7 on 2020-06-28 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone_price', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deces9_domicile_price_province', to='base.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentManualy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_man_f_l_name', models.CharField(max_length=50)),
                ('gender', models.TextField(max_length=2)),
                ('DM_mother', models.CharField(max_length=64)),
                ('DM_father', models.CharField(max_length=64)),
                ('DM_death_date', models.DateField(default=django.utils.timezone.now, verbose_name='at_deces5_dom_date_deces')),
                ('first_witness', models.CharField(max_length=60)),
                ('second_witness', models.CharField(max_length=60)),
                ('rejection_msg', models.TextField(blank=True, null=True)),
                ('secretary_validated', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('DM_origin_quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_deces3_dom_quartier_origine', to='base.Quarter')),
                ('DM_residence_quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_deces4_dom_quartier_resi_defunt', to='base.Quarter')),
                ('quarter_leader', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='at_deces6_SupervisorNaD', to='base.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_deces1_dom_declarant', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='at_deces2_dom_zone', to='base.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DM_date', models.DateField(default=django.utils.timezone.now, verbose_name='at_deces_dom_date_deces')),
                ('rejection_msg', models.TextField(blank=True, null=True)),
                ('secretary_validated', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('dead_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_deces_dom_defunt', to=settings.AUTH_USER_MODEL)),
                ('first_witness', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='at_deces_dom_T1', to='base.Profile')),
                ('quarter_leader', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='at_deces_dom_quater_leader', to='base.Profile')),
                ('residence_quarter_DM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_deces_dom_quartier_resi_defunt', to='base.Quarter')),
                ('second_witness', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='at_deces_dom_T2', to='base.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_deces_dom_declarant', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='ZoneNaD', to='base.Zone')),
            ],
        ),
    ]
