# Generated by Django 3.0.7 on 2020-06-28 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incognito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incognito_gender', models.CharField(max_length=20)),
                ('incognito_last_name', models.CharField(max_length=20)),
                ('incognito_first_name', models.CharField(max_length=20)),
                ('incognito_father_name', models.CharField(max_length=20)),
                ('incognito_mother_name', models.CharField(max_length=20)),
                ('incognito_birthday_name', models.CharField(max_length=20)),
                ('incognito_birth_quarter', models.CharField(max_length=20)),
                ('incognito_birth_zone', models.CharField(max_length=20)),
                ('incognito_birth_province', models.CharField(max_length=20)),
                ('incognito_nationality', models.CharField(max_length=20)),
                ('incognito_marital_statute', models.CharField(max_length=20)),
                ('incognito_marital_CNI', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone_price', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banmariage_price_province', to='base.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rejection_msg', models.TextField(blank=True, null=True)),
                ('secretary_validated', models.BooleanField(null=True)),
                ('ready', models.BooleanField(default=False)),
                ('bride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banmariage_bride', to='base.Profile')),
                ('residence_quarter', models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banmariage_residence', to='base.Quarter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banmariage_groom', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banmariage_zone', to='base.Zone')),
                ('zone_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banmariage_province_payment', to='base.PaymentZone')),
            ],
        ),
    ]
