# Generated by Django 3.0.7 on 2020-06-28 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone_price', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_app_parc_price_province', to='base.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriety_surfaces_a', models.IntegerField()),
                ('propriety_surfaces_ca', models.IntegerField()),
                ('propriety_contenency', models.CharField(max_length=100)),
                ('rejection_msg', models.TextField(blank=True, null=True)),
                ('secretary_validated', models.BooleanField(null=True)),
                ('ready', models.BooleanField(default=False)),
                ('propriety_quarter', models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_app_parc_propr', to='base.Quarter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_app_parc_user', to=settings.AUTH_USER_MODEL)),
                ('user_residence_quarter', models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_app_parc_residence_quarter_user', to='base.Quarter')),
                ('zone_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_app_parc_province_payment', to='base.PaymentZone')),
            ],
        ),
    ]
