# Generated by Django 3.0.7 on 2020-06-28 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone_price', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etatcivil_etat_civil_price_province', to='base.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('marital_statut', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=64)),
                ('payment_serial', models.CharField(max_length=64)),
                ('rejection_msg', models.TextField(blank=True, null=True)),
                ('secretary_validated', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('residence_quarter', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='etatcivil_Quartier_EtatCivil', to='base.Quarter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etatcivil_Beneficiaire_EtatCivil', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='etatcivil_Zone_EtatCivil', to='base.Zone')),
            ],
        ),
    ]
